Remove SSH functionality from Proxstar
ComputerScienceHouse/proxstar pull request #158
Opened 2022-07-30 02:45 UTC by WillNilges

Now that VNC is over `wss://`, we don't need it.

2022-07-31 01:53 UTC, WillNilges commented
In regards to the TODOs, I can use Redis to store the targets file data :0

2022-08-12 04:44 UTC, WillNilges commented on proxstar/tasks.py
> +                    redis_conn.delete(vnc_token_key)
This is probably unnecessary, to be honest, and would cause more problems than it's worth.

2022-08-12 04:46 UTC, WillNilges commented
```
diff --git a/proxstar/tasks.py b/proxstar/tasks.py
index a94ff70..0bf006f 100644
--- a/proxstar/tasks.py
+++ b/proxstar/tasks.py
@@ -151,7 +151,7 @@ def process_expiring_vms_task():
                             vm.name, vm.id
                         )
                     )
-                    vmid = vm['vmid'] 
+                    vmid = vm['vmid']
                     vnc_token_key = f'vnc_token|{vmid}'
                     vnc_token = redis_conn.get(vnc_token_key).decode('utf-8')
                     delete_vnc_target(token=vnc_token)

```

Thank you black, very cool.

2022-08-12 14:17 UTC, WillNilges commented
bro smh

2022-08-18 01:56 UTC, jabbate19 requested changes
Debug Print, Thats ab it

2022-08-18 03:32 UTC, jabbate19 approved these changes
Chom

2022-08-18 23:49 UTC, WillNilges commented
gonna rebase this a little because I want to be able to bisect this if the tasks break.

2022-08-19 00:02 UTC, merged